#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HIPAD_ROOT="${HIPAD_PNN_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
MAP_ROOT="${MAP_ROOT:-$(dirname "${HIPAD_ROOT}")}"
PNN_ROOT="${HIPAD_ROOT}/pnn"
PYTHON_BIN="${PYTHON_BIN:-python}"

OLD_DATA="${PNN_OLD_DATA:-${HIPAD_ROOT}/data/pnn/time_aligned_v3/train_old.pt}"
NEW_DATA="${PNN_NEW_DATA:-${HIPAD_ROOT}/data/pnn/static_v3/train_new_with_hipad_plan.pt}"
SUPERVISION="${PNN_SUPERVISION_DATA:-${HIPAD_ROOT}/data/pnn/static_v31/solid_lane_supervision.pt}"
RUN_DIR="${PNN_SAVE_DIR:-${HIPAD_ROOT}/outputs/pnn_physical_joint_scratch_v2}"
LOG_DIR="${PNN_LOG_DIR:-${HIPAD_ROOT}/outputs/logs/physical_joint_scratch_v2}"

for path in "${OLD_DATA}" "${NEW_DATA}" "${SUPERVISION}"; do
    [[ -s "${path}" ]] || { echo "ERROR: missing ${path}" >&2; exit 1; }
done

ALIGNMENT_VERSION="$(PYTHONPATH="${HIPAD_ROOT}:${PYTHONPATH:-}" "${PYTHON_BIN}" -c 'from pnn_temporal_alignment import ALIGNMENT_VERSION; print(ALIGNMENT_VERSION)')"
"${PYTHON_BIN}" "${SCRIPT_DIR}/audit_pnn_actor_alignment.py" \
    --input "${OLD_DATA}" --expected-version "${ALIGNMENT_VERSION}"

if [[ -e "${RUN_DIR}/checkpoints/last.pth" && "${PNN_ALLOW_RESUME:-0}" != "1" ]]; then
    echo "ERROR: ${RUN_DIR} already contains last.pth; set PNN_ALLOW_RESUME=1 to continue" >&2
    exit 2
fi

mkdir -p "${RUN_DIR}/checkpoints" "${LOG_DIR}"
echo "[physical-joint-v2] random initialization; solid-lane supervision is mandatory"
echo "[physical-joint-v2] control accel=[-4.05,2.40] steer=[-1.066,1.066]"
echo "[physical-joint-v2] run=${RUN_DIR} epochs=${PNN_TOTAL_EPOCHS:-200}"

PNN_GPUS="${PNN_GPUS:-0,1,2,3}" \
PYTHON_BIN="${PYTHON_BIN}" \
PNN_OLD_DATA="${OLD_DATA}" \
PNN_NEW_DATA="${NEW_DATA}" \
PNN_SUPERVISION_DATA="${SUPERVISION}" \
PNN_REQUIRE_SOLID_LANE_SUPERVISION=1 \
PNN_CONTROL_CKPT= \
PNN_TEACHER_CKPT= \
PNN_INITIAL_RESUME_CKPT= \
PNN_SAVE_DIR="${RUN_DIR}" \
LOG_DIR="${LOG_DIR}" \
TOTAL_EPOCHS="${PNN_TOTAL_EPOCHS:-200}" \
SEGMENT_EPOCHS="${PNN_SEGMENT_EPOCHS:-10}" \
PNN_BATCH_SIZE="${PNN_BATCH_SIZE:-48}" \
PNN_STAGE1_NUM_WORKERS="${PNN_STAGE1_NUM_WORKERS:-1}" \
PNN_LR_CONTROL="${PNN_LR_CONTROL:-2e-5}" \
PNN_REQUIRE_HIPAD_PLAN_2HZ=1 \
PNN_CONTROL_DECODE_MIN_ACCEL=-4.05 \
PNN_CONTROL_DECODE_MAX_ACCEL=2.40 \
PNN_CONTROL_DECODE_MAX_STEER=1.066 \
PNN_ACTUATOR_MAX_ACCEL=2.40 \
PNN_ACTUATOR_MAX_DECEL=4.05 \
PNN_ACTUATOR_MAX_STEER=1.066 \
PNN_LAMBDA_ACTUATOR_FEASIBILITY=0.25 \
PNN_LAMBDA_RISK_EARLY_BRAKE=0.5 \
PNN_RISK_EARLY_BRAKE_STEPS=5 \
PNN_RISK_EARLY_BRAKE_ACCEL_CEILING=0.0 \
PNN_CONTROL_WEIGHT_START_EPOCH=1000000 \
PNN_WEIGHT_UPDATE_START_EPOCH=1000000 \
PNN_LAMBDA_WEIGHT_TRAJ=0 \
PNN_TRAIN_SOFT_CONSTRAINT_LAMBDAS=0 \
PNN_TRAIN_RAW_COLLISIONS=1 \
PNN_OFFICIAL_FRAME_ACR_ENABLED=1 \
PNN_OFFICIAL_FRAME_ACR_PNN_ONLY=1 \
PNN_OFFICIAL_RASTER_ACTOR_PADDING=0.12 \
PNN_OFFICIAL_RASTER_ACTOR_DILATION_PIXELS=0.5 \
PNN_LAMBDA_OFFICIAL_FRAME_ACR="${PNN_LAMBDA_OFFICIAL_FRAME_ACR:-0.40}" \
PNN_OFFICIAL_FRAME_ACR_MARGIN=1.0 \
PNN_OFFICIAL_FRAME_ACR_TEMPERATURE=0.25 \
PNN_OFFICIAL_FRAME_ACR_TIME_WEIGHTS="8,8,6,6,4,4" \
PNN_LAMBDA_OFFICIAL_FRAME_ANCHOR="${PNN_LAMBDA_OFFICIAL_FRAME_ANCHOR:-2.0}" \
PNN_OFFICIAL_FRAME_ANCHOR_REQUIRE_LANE_SAFE=1 \
PNN_OFFICIAL_FRAME_ANCHOR_INCLUDE_PREVIOUS=1 \
PNN_OFFICIAL_FRAME_ANCHOR_TIME_WEIGHTS="8,8,6,6,4,4" \
PNN_LAMBDA_SAFE_PARENT_DISTILL=0 \
PNN_LAMBDA_OFFICIAL_FRAME_LANE_GUARD="${PNN_LAMBDA_OFFICIAL_FRAME_LANE_GUARD:-6.0}" \
PNN_OFFICIAL_FRAME_LANE_GUARD_MARGIN=0.20 \
PNN_OFFICIAL_FRAME_LANE_GUARD_INCLUDE_LANE_HITS=1 \
PNN_OFFICIAL_FRAME_LANE_GUARD_SELF_GATE_THRESHOLD=0.0 \
PNN_OFFICIAL_FRAME_LANE_GUARD_INCLUDE_PREVIOUS=1 \
PNN_OFFICIAL_FRAME_LANE_GUARD_INCLUDE_FUTURE=0 \
PNN_OFFICIAL_FRAME_LANE_GUARD_TIME_WEIGHTS="1,1,2,4,8,14" \
PNN_LAMBDA_EGO_OBJECT_SAFETY=0 \
PNN_LAMBDA_GT_REFERENCE_LANE=0 \
PNN_LAMBDA_METRIC_LANE="${PNN_LAMBDA_METRIC_LANE:-5.0}" \
PNN_METRIC_LANE_MARGIN=0.05 \
PNN_METRIC_LANE_USE_GT_SAFE_SIDE=1 \
PNN_METRIC_LANE_TIME_WEIGHTS="1,1,2,4,8,14" \
PNN_METRIC_LANE_HARD_MAX_WEIGHT=0.75 \
PNN_DISABLE_PREDICTED_LANE_LOSSES=1 \
PNN_LAMBDA_ROLLOUT_COMFORT=1.0 \
PNN_STATS_QUANTILE_LOW=0.005 \
PNN_STATS_QUANTILE_HIGH=0.995 \
PNN_CLAMP_NORMALIZED_INPUTS=1 \
PNN_EVAL_EACH_EPOCH=false \
bash "${SCRIPT_DIR}/run_pnn_control_pretrain_segments.sh"

echo "[physical-joint-v2] complete: ${RUN_DIR}/checkpoints"
