#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HIPAD_ROOT="${HIPAD_PNN_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
MAP_ROOT="${MAP_ROOT:-$(dirname "${HIPAD_ROOT}")}"
PNN_ROOT="${HIPAD_ROOT}/pnn"
PYTHON_BIN="${PYTHON_BIN:-python}"

# 闭环优先分支：保持训练样本和部署接口不变，只重新定义安全/推进的优先关系。
OLD_DATA="${PNN_OLD_DATA:-${HIPAD_ROOT}/data/pnn/time_aligned_v3/train_old.pt}"
NEW_DATA="${PNN_NEW_DATA:-${HIPAD_ROOT}/data/pnn/static_v3/train_new_with_hipad_plan.pt}"
SUPERVISION="${PNN_SUPERVISION_DATA:-${HIPAD_ROOT}/data/pnn/static_v31/solid_lane_supervision.pt}"
PARENT="${PNN_PARENT_CKPT:-${HIPAD_ROOT}/checkpoints/pnn_control.pth}"
RUN_DIR="${PNN_SAVE_DIR:-${HIPAD_ROOT}/outputs/pnn_closedloop_priority_stage1}"
LOG_DIR="${PNN_LOG_DIR:-${HIPAD_ROOT}/outputs/logs/closedloop_priority_stage1}"

for path in "${OLD_DATA}" "${NEW_DATA}" "${SUPERVISION}" "${PARENT}"; do
    [[ -s "${path}" ]] || { echo "ERROR: missing ${path}" >&2; exit 1; }
    [[ "${path}" != *"/evaluation/"* ]] || {
        echo "ERROR: evaluation result cannot be training input: ${path}" >&2
        exit 2
    }
done
if [[ -s "${RUN_DIR}/checkpoints/last.pth" && "${PNN_ALLOW_RESUME:-0}" != "1" ]]; then
    echo "ERROR: ${RUN_DIR}/checkpoints/last.pth exists; set PNN_ALLOW_RESUME=1 to resume" >&2
    exit 3
fi

mkdir -p "${RUN_DIR}/checkpoints" "${LOG_DIR}"
sha256sum "${OLD_DATA}" "${NEW_DATA}" "${SUPERVISION}" "${PARENT}" \
    > "${RUN_DIR}/training_inputs.sha256"

echo "[closedloop-priority] parent=${PARENT}"
echo "[closedloop-priority] run=${RUN_DIR}"
echo "[closedloop-priority] sparse targets are route intent; actor/lane safety gates route tracking"
echo "[closedloop-priority] checkpoint selection uses closed-loop DS/SR, not open-loop L2"

PNN_GPUS="${PNN_GPUS:-0,1,2,3}" \
PYTHON_BIN="${PYTHON_BIN}" \
PNN_OLD_DATA="${OLD_DATA}" \
PNN_NEW_DATA="${NEW_DATA}" \
PNN_SUPERVISION_DATA="${SUPERVISION}" \
PNN_REQUIRE_GT_ACTOR_BOXES=1 \
PNN_REQUIRE_SOLID_LANE_SUPERVISION=1 \
PNN_REQUIRE_HIPAD_PLAN_2HZ=1 \
PNN_CONTROL_CKPT="${PARENT}" \
PNN_TEACHER_CKPT="${PARENT}" \
PNN_INITIAL_RESUME_CKPT= \
PNN_SAVE_DIR="${RUN_DIR}" \
LOG_DIR="${LOG_DIR}" \
TOTAL_EPOCHS="${PNN_TOTAL_EPOCHS:-12}" \
SEGMENT_EPOCHS="${PNN_SEGMENT_EPOCHS:-4}" \
PNN_BATCH_SIZE="${PNN_BATCH_SIZE:-48}" \
PNN_STAGE1_NUM_WORKERS="${PNN_NUM_WORKERS:-1}" \
PNN_MAX_TRAIN_BATCHES="${PNN_MAX_TRAIN_BATCHES:-0}" \
PNN_LR_CONTROL="${PNN_LR_CONTROL:-1e-6}" \
PNN_RESUME_OPTIMIZER_STATE=0 \
PNN_OVERRIDE_RESUME_LR=1 \
PNN_CONTROL_UPDATE_START_EPOCH=0 \
PNN_CONTROL_WEIGHT_START_EPOCH=1000000 \
PNN_WEIGHT_UPDATE_START_EPOCH=1000000 \
PNN_LAMBDA_WEIGHT_TRAJ=0 \
PNN_DEFAULT_COST_WEIGHTS="1.0,2.0,0.6,2.0,3.0,2.0,1.2,10.0" \
PNN_ROUTE_TARGET_AUG_PROBABILITY="${PNN_ROUTE_TARGET_AUG_PROBABILITY:-0.35}" \
PNN_ROUTE_TARGET_LONGITUDINAL_SCALE_STD="${PNN_ROUTE_TARGET_LONGITUDINAL_SCALE_STD:-0.03}" \
PNN_ROUTE_TARGET_LATERAL_JITTER_STD="${PNN_ROUTE_TARGET_LATERAL_JITTER_STD:-0.15}" \
PNN_ROUTE_TARGET_MIDDLE_DROPOUT="${PNN_ROUTE_TARGET_MIDDLE_DROPOUT:-0.10}" \
PNN_ROUTE_TRACK_RISK_GATE_GAIN="${PNN_ROUTE_TRACK_RISK_GATE_GAIN:-3.0}" \
PNN_ROUTE_TRACK_RISK_MIN_WEIGHT="${PNN_ROUTE_TRACK_RISK_MIN_WEIGHT:-0.15}" \
PNN_ROUTE_TRACK_LANE_RISK_GAIN="${PNN_ROUTE_TRACK_LANE_RISK_GAIN:-1.0}" \
PNN_CONTROL_DECODE_MIN_ACCEL=-4.05 \
PNN_CONTROL_DECODE_MAX_ACCEL=2.40 \
PNN_CONTROL_DECODE_MAX_STEER=1.066 \
PNN_ACTUATOR_MAX_ACCEL=2.40 \
PNN_ACTUATOR_MAX_DECEL=4.05 \
PNN_ACTUATOR_MAX_STEER=1.066 \
PNN_LAMBDA_ACTUATOR_FEASIBILITY=0.5 \
PNN_TRAIN_RAW_COLLISIONS=1 \
PNN_OFFICIAL_FRAME_ACR_ENABLED=1 \
PNN_OFFICIAL_FRAME_ACR_PNN_ONLY=1 \
PNN_OFFICIAL_FRAME_ACR_REQUIRE_PERCEIVED_ACTOR=1 \
PNN_PERCEIVED_ACTOR_MATCH_RADIUS=3.0 \
PNN_PERCEIVED_ACTOR_COLLISION_MARGIN=0.75 \
PNN_OFFICIAL_RASTER_ACTOR_PADDING=0.12 \
PNN_OFFICIAL_RASTER_ACTOR_DILATION_PIXELS=0.5 \
PNN_LAMBDA_OFFICIAL_FRAME_ACR=0.75 \
PNN_OFFICIAL_FRAME_ACR_MARGIN=0.75 \
PNN_OFFICIAL_FRAME_ACR_TEMPERATURE=0.25 \
PNN_OFFICIAL_FRAME_ACR_TIME_WEIGHTS="10,10,8,6,4,3" \
PNN_LAMBDA_RISK_EARLY_BRAKE=0.20 \
PNN_RISK_EARLY_BRAKE_STEPS=8 \
PNN_RISK_EARLY_BRAKE_ACCEL_CEILING=0.0 \
PNN_LAMBDA_PERCEPTION_GATED_BRAKE=0 \
PNN_LAMBDA_SAFE_PARENT_DISTILL=4.0 \
PNN_SAFE_PARENT_DISTILL_REQUIRE_PARENT_LANE_SAFE=1 \
PNN_LAMBDA_SAFE_PARENT_CONTROL_DISTILL=2.0 \
PNN_SAFE_PARENT_CONTROL_DISTILL_BETA=0.10 \
PNN_SAFE_PARENT_CONTROL_DISTILL_STEER_WEIGHT=1.5 \
PNN_LAMBDA_OFFICIAL_FRAME_ANCHOR=0 \
PNN_LAMBDA_OFFICIAL_FRAME_LANE_GUARD=2.0 \
PNN_OFFICIAL_FRAME_LANE_GUARD_MARGIN=0.12 \
PNN_OFFICIAL_FRAME_LANE_GUARD_INCLUDE_LANE_HITS=1 \
PNN_OFFICIAL_FRAME_LANE_GUARD_INCLUDE_PREVIOUS=1 \
PNN_OFFICIAL_FRAME_LANE_GUARD_INCLUDE_FUTURE=1 \
PNN_OFFICIAL_FRAME_LANE_GUARD_TIME_WEIGHTS="1,1,2,4,8,14" \
PNN_LAMBDA_EGO_OBJECT_SAFETY=0 \
PNN_LAMBDA_GT_REFERENCE_LANE=0 \
PNN_LAMBDA_METRIC_LANE=2.0 \
PNN_METRIC_LANE_MARGIN=0.05 \
PNN_METRIC_LANE_USE_GT_SAFE_SIDE=1 \
PNN_METRIC_LANE_TIME_WEIGHTS="1,1,2,4,8,14" \
PNN_METRIC_LANE_HARD_MAX_WEIGHT=0.75 \
PNN_DISABLE_PREDICTED_LANE_LOSSES=1 \
PNN_LAMBDA_OBS_CLEARANCE=0.20 \
PNN_OBS_CLEARANCE_MARGIN_VEH=2.5 \
PNN_OBS_CLEARANCE_MARGIN_PED=1.8 \
PNN_OBS_CLEARANCE_TOPK=3 \
PNN_OBS_CLEARANCE_TIME_WEIGHTS="2.0,1.5,1.0" \
PNN_LAMBDA_ROUTE_SPEED_EXCESS=0.5 \
PNN_ROUTE_SPEED_MARGIN=0.5 \
PNN_ROUTE_SPEED_BRAKE_TRIGGER_MARGIN=0.5 \
PNN_ROUTE_SPEED_POS_ACCEL_THRESHOLD=0.2 \
PNN_ROUTE_SPEED_BRAKE_WEIGHT=0.4 \
PNN_LAMBDA_ROLLOUT_COMFORT=0.5 \
PNN_TRAIN_SOFT_CONSTRAINT_LAMBDAS=0 \
PNN_STATS_QUANTILE_LOW=0.005 \
PNN_STATS_QUANTILE_HIGH=0.995 \
PNN_CLAMP_NORMALIZED_INPUTS=1 \
PNN_TRAIN_PROXY_METRICS=1 \
PNN_EVAL_EACH_EPOCH=false \
bash "${SCRIPT_DIR}/run_pnn_control_pretrain_segments.sh"

echo "[closedloop-priority] complete: ${RUN_DIR}/checkpoints"
